---
  - name: Setup docker for alpine linux
    block:
      - name: install packages
        apk:
          name: bash,tar,rsync,zip
          state: present
          update_cache: yes

      - name: install packages
        apk:
          name: build-base,git,make,vim
          state: present
          update_cache: yes
        when: docker_build_environment

      - name: install additional packages
        apk:
          name: "{{ item }}"
          state: present
        with_items: "{{ required_packages }}"

      - name: install python packages
        apk:
          name: python-dev,py-pip,py-openssl
          state: latest
          update_cache: yes

      - name: update all installed packages
        apk:
          upgrade: yes

      # - name: choose a fast and reliable mirror
      #   raw: setup-apkrepos -f

      - name: install docker
        apk:
          name: docker
          state: present
          update_cache: yes
          repository: "{{ docker_alpine_repo }}"
        ignore_errors: true

      - name: clean up cache packages
        raw: rm -rf /var/cache/apk/*

      - name: start docker
        service:
          name: docker
          state: started

      - name: gather facts
        setup: filter="*"

      - name: start docker
        service:
          name: docker
          enabled: yes
          state: started
    when: ansible_distribution == "Alpine"