---
- name: Setup docker for alpine linux
  block:
    - name: install packages
      apk:
        name: bash,ca-certificates,rsync,tar,zip
        state: present
        update_cache: yes

    - name: import signing key
      get_url:
        url: https://raw.githubusercontent.com/sgerrand/alpine-pkg-glibc/master/sgerrand.rsa.pub
        dest: /etc/apk/keys/sgerrand.rsa.pub
        mode: 0440
      when: docker_glibc_environment

    - name: download glibc package
      get_url:
        url: "{{ glibc_package_url }}"
        dest: /tmp/glibc-2.26-r0.apk
        mode: 0644
      when: docker_glibc_environment

    - name: install packages
      apk:
        name: build-base,musl-dev,git,make,gcc,g++,vim
        state: present
        update_cache: yes
      when: docker_build_environment
      
    - name: install glibc
      raw: apk add /tmp/glibc-2.26-r0.apk
      when: docker_glibc_environment

    - name: install additional packages
      apk:
        name: "{{ item }}"
        state: present
      with_items: "{{ required_packages }}"

    - name: install python packages
      apk:
        name: python-dev,py-pip,py-openssl
        state: latest
        update_cache: yes

    - name: update all installed packages
      apk:
        upgrade: yes

    # - name: choose a fast and reliable mirror
    #   raw: setup-apkrepos -f

    - name: install docker
      apk:
        name: docker
        state: present
        update_cache: yes
        repository: "{{ docker_alpine_repo }}"
      ignore_errors: true

    - name: clean up cache packages
      raw: rm -rf /var/cache/apk/*

    - name: start docker
      service:
        name: docker
        state: started

    - name: gather facts
      setup: filter="*"

    - name: start docker
      service:
        name: docker
        enabled: yes
        state: started
  when: ansible_distribution == "Alpine"