---
- name: Setup docker for alpine linux
  block:
    - name: install additional packages
      apk:
        name: "{{ item }}"
        state: present
      with_items: "{{ required_packages }}"

    - name: install python packages
      pip:
        name: "{{ item }}"
      with_items: "{{ required_pip }}"

    - name: update all installed packages
      apk:
        upgrade: yes

    - name: install docker
      apk:
        name: docker
        state: present
        update_cache: yes
        repository: "{{ docker_alpine_repo }}"
      ignore_errors: true

    - name: clean up cache packages
      raw: rm -rf /var/cache/apk/*

    - name: start docker
      service:
        name: docker
        state: started

    - name: gather facts
      setup: filter="*"
  when: ansible_os_family == "Alpine"