---
- name: Setup debian
  block:
    - name: install dependent packages
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg2
        - software-properties-common
        - dirmngr
        - libffi-dev
        - python-dev
        - python-setuptools

    - name: run apt update
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_distribution == 'Debian'
      register: apt_result
      until: apt_result|success
      retries: 3
      delay: 1
      ignore_errors: yes

    - name: retry if needed using command apt-get update
      command: apt-get update
      when: apt_result|failed

    - name: remove python-pip
      apt:
        name: python-pip
        state: absent

    - name: check pip version
      shell: pip --version | cut -d" " -f2
      register: pip_check
      ignore_errors: yes

    - name: install latest pip
      easy_install:
        name: pip
        executable: "{{ debian_easy_install_bin }}"
        state: latest
      when: pip_check.stdout.find("{{ pip_version }}") == -1

    - name: remove docker-py
      pip:
        name: docker-py
        state: absent

    - name: install python packages
      pip:
        name: virtualenv,docker-compose,uptime

    - name: install python packages
      pip:
        name: "{{ item }}"
      with_items: "{{ required_pip }}"

    - name: verify gpg key installed
      command: apt-key list
      no_log: yes
      register: apt_key_check

    - name: update gpg key for docker repo
      command: apt-key adv --keyserver {{ docker_apt_recv_key_server }} --recv-keys {{ docker_apt_recv_key }}
      ignore_errors: yes
      become: yes
      when: apt_key_check.stdout.find("Docker Release Tool") == -1

    - name: add docker repo
      apt_repository:
        repo: "{{ docker_apt_repo }}"
        state: present

    - name: create apt pin
      copy:
        dest: "{{ item.file }}"
        content: |
          Package: {{ item.package }}
          Pin: {{ item.pin }}
          Pin-Priority: {{ item.pin_priority }}
        mode: 0444
        owner: root
        group: root
      with_items: "{{ docker_apt_pin }}"

    - name: run apt update
      apt:
        update_cache: yes
      register: apt_result
      until: apt_result|success
      retries: 3
      delay: 1
      ignore_errors: yes

    - name: retry if needed using command apt-get update
      command: apt-get update
      when: apt_result|failed

    - name: install docker
      apt:
        name: "docker-engine={{ docker_version }}~ce-0~debian-{{ ansible_distribution_release }}"
        update_cache: yes
        state: present
        force: yes
        cache_valid_time: "{{ apt_cache_valid_time }}"

    - name: create filesystem paths
      file:
        dest: "{{ docker_daemon_config_file | dirname }}"
        owner: root
        group: root
        state: directory

    - name: create daemon config
      template:
        src: daemon.json.j2
        dest: "{{ docker_daemon_config_file }}"
        mode: 0644
        owner: root
        group: root
      notify:
        - restart docker
  when: ansible_os_family == "Debian"
