---
- name: check docker version
  shell: "{{ docker_bin }} --version"
  register: docker_check
  ignore_errors: yes
  changed_when: no

- name: Run prereqs
  include_tasks: prereqs.yml
  when: docker_version not in docker_check.stdout and docker_clean_install

- name: Run setup
  include_tasks: setup.yml

- name: Setup alpine
  include_tasks: alpine.yml

- name: Setup debian
  include_tasks: debian.yml

- name: Setup redhat
  include_tasks: redhat.yml

- name: Start service
  include_tasks: service.yml
