---
# - name: create docker group
#   group:
#     name: "{{ docker_group }}"
#     system: yes
#     state: present

# - name: create docker user
#   user:
#     name: "{{ docker_user }}"
#     state: present
#     comment: "{{ docker_user }}"
#     group: "{{ docker_group }}"
#     shell: /sbin/nologin
#     createhome: no
#     system: yes

- name: install python packages
  pip:
    name: requests