---
- name: Setup redhat
  block:
    - name: update all packages
      yum:
        name: "*"
        state: latest

    - name: add epel repo
      yum:
        name: epel-release
        state: latest

    - name: remove python-pip
      yum:
        name: "{{ item }}"
        state: absent
      with_items:
        - python-pip
        - python-wheel

    - name: install latest pip
      raw: easy_install pip

    - name: remove docker-py
      pip:
        name: docker-py
        state: absent

    - name: install python packages
      pip: 
        name: virtualenv,docker-compose,uptime

    - name: install python packages
      pip: 
        name: "{{ item }}"
      with_items: "{{ required_pip }}"

    - name: install docker
      shell: curl -fsSL https://get.docker.com/ | sh
  when: ansible_os_family == "RedHat"
