---
- name: Setup redhat
  block:
    - name: update all packages
      yum:
        name: "*"
        state: latest

    - name: add epel repo
      yum:
        name: epel-release
        state: latest

    - name: remove python-pip
      yum:
        name: "{{ item }}"
        state: absent
      with_items:
        - python-pip
        - python-wheel

    - name: install latest pip
      easy_install:
        name: pip
        executable: "{{ redhat_easy_install_bin }}"
        state: latest

    - name: remove docker-py
      pip:
        name: docker-py
        state: absent

    - name: install python packages
      pip: 
        name: virtualenv,docker-compose,uptime

    - name: install python packages
      pip: 
        name: "{{ item }}"
      with_items: "{{ required_pip }}"

    - name: create filesystem paths
      file:
        dest: "{{ docker_daemon_config_file | dirname }}"
        owner: root
        group: root
        state: directory

    - name: create daemon config
      template:
        src: daemon.json.j2
        dest: "{{ docker_daemon_config_file }}"
        mode: 0644
        owner: root
        group: root
      notify:
        - restart docker

    - name: install docker
      shell: curl -fsSL https://get.docker.com/ | sh
  when: ansible_os_family == "RedHat"
