---
- name: Check for init.d service
  set_fact:
    is_service: yes
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "14"

- name: Check for systemd service
  set_fact:
    is_systemd: yes
  when: (ansible_os_family in [ "RedHat", "ClearOS"] and ansible_distribution_major_version >= "7") or (ansible_distribution == "Ubuntu" and ansible_distribution_major_version >= "16") or (ansible_distribution == "Debian" and ansible_distribution_major_version >= "8")

- block:
  - name: Enable docker service
    service:
      name: docker
      enabled: yes
      state: started
  when: is_service

- block:
  - name: Enable docker systemd service
    systemd:
      name: docker
      enabled: yes
      daemon-reload: yes
      state: started
  when: is_systemd